services:
  - type: web
    name: kevin-personal-website-cms
    runtime: node
    plan: free
    rootDir: cms
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: NODE_VERSION
        value: 20.15.1
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
